language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgtest-dev
      - lcov
      - rubygems
      - g++-4.8
                
before_install:
    # Build GTest
    - pushd "`pwd`"
    - sudo mkdir /usr/src/gtest/build
    - cd /usr/src/gtest/build
    - sudo cmake .. -DBUILD_SHARED_LIBS=1
    - sudo make -j 4
    - sudo ln -s /usr/src/gtest/build/libgtest.so /usr/lib/libgtest.so
    - sudo ln -s /usr/src/gtest/build/libgtest_main.so /usr/lib/libgtest_main.so
    - popd
    # Install lcoveralls
    - gem install lcoveralls

before_script:
    - mkdir build && cd build
    - cmake ..

script:
    - make
    - ../coverage.sh

after_sucess:
    - lcoveralls "src/tdigest_filtered.info"
