language: cpp

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update
    - sudo apt-get install -qq libgtest-dev
    # Build GTest
    - pushd "`pwd`"
    - sudo mkdir /usr/src/gtest/build
    - cd /usr/src/gtest/build
    - sudo cmake .. -DBUILD_SHARED_LIBS=1
    - sudo make -j 4
    - sudo ln -s /usr/src/gtest/build/libgtest.so /usr/lib/libgtest.so
    - sudo ln -s /usr/src/gtest/build/libgtest_main.so /usr/lib/libgtest_main.so
    - popd
    # Install lcov + rubygems
    - sudo apt-get install -qq lcov rubygems
    - gem install lcoveralls

before_script:
    - mkdir build && cd build
    - cmake ..

script:
    - make
    - ../coverage.sh

after_sucess:
    - lcoveralls "src/tdigest_filtered.info"
